bot:
  prefix: $
  token:

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fpp
    username: postgres
    password: 3310TaO_u
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true